language: r
sudo: required
warnings_are_errors: false
r_check_args: "--no-build-vignettes --no-manual --timings"
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
  - CRAN: http://cran.rstudio.com
  - NOT_CRAN: true
before_install:
- openssl aes-256-cbc -K $encrypted_43a2e4232448_key -iv $encrypted_43a2e4232448_iv -in tests/testthat/setup.tar.enc -out tests/testthat/setup.tar -d
- tar xvf tests/testthat/setup.tar -C tests/testthat
r_github_packages:
- jimhester/covr
r_binary_packages:
- XML
- plyr
- dplyr
- testthat
- httr
r_packages:
- rmarkdown
after_success:
- Rscript -e 'library(covr);codecov()'
